### ISSUE TITLE
streaming

### ISSUE THREAD

**Issue by FabioWielewski** [ronschaeffer/video_doorbell_voice_repsonse#1]
good job, i would like to know if you are working on microphone streaming?

**Comment by ronschaeffer** [comment]
Thanks. No, I have not found a viable solution for audio capture using the ESP32 and ESPHome. Also, streaming from a phone (for example) down to the doorbell would also require a different audio playback board in the doorbell.  The DFPlayer Mini can only play MP3s which are stored on the inserted SD card. And, those files have to be added to the SD card beforehand. They cannot be added through the link to the ESP32. I'll keep an eye out, but I doubt that mic streaming will ever be possible for this project with the ESP32.
